apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: golang
spec:
  releaseName: nginx-ingress-controller
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    image:
      registry: docker.io
      repository: qorbani/golang-hello-world
      tag: latest
    service:
      type: NodePort
